# Generated by Django 5.0.2 on 2025-04-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_daily_use_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/800x600.png?text=Category+Image', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/800x600.png?text=Product+Image', max_length=500),
        ),
    ]
